### ISSUE TITLE
Every providers are downs

### ISSUE THREAD

**Issue by quentindurpoix** [tillnagel/unfolding#153] opened 2017-11-03 10:30 UTC
Hi,
I'm working on a project where I need to display a lot of markers on maps. Processing seems to me very great to do it. But as I could see, the only librairy allowing me to work on maps is on Processing 2. 
But when I'm trying to display Maps, it seems that servers host are downs. I tried every different providers but it doesn't work either. Do you know how can I do it ? 

Thanks, Quentin

**Comment by eialbur** [comment] 2017-12-26 21:39
I appear to be having the same (or similar) problem. I just (today) downloaded Unfolding Maps (eclipse). I am just trying to run some examples. No matter what map provider I supply, I get the following types of message:
The file http://a.www.toolserver.org/tiles/bw-mapnik/13/4402/2687.png contains bad image data, or may not be an image.

Here is how I try to supply a different provider (in this case Google):
map = new UnfoldingMap(this, new Google.GoogleMapProvider());

I guess that it is trying to use a default server during initialization and then overwrite with the specified provider. I have tried going to the url in the error message in my browser, and I can bring down the tile. I tried turning off the Windows firewall, but still get the message.

Any help would be appreciated.

**Comment by eialbur** [comment] 2017-12-26 22:18
Ok - I may have discovered the issue. I found one example that worked. Instead of supplying a hard-coded string for the main class when calling PApplet.main it used XXX.class.getName(). So I started checking, and it appears that the examples directory was reorganized but the hard-coded strings for the main class were not. When I substitute XXX.class.getName() the examples appear to start working.

Frankly, I'm confused by this because with the incorrect string everything still appeared to work ... except for the map provider. Maybe you can explain this to me .. in the meantime I'm rocking & rolling again.

**Comment by tillnagel** [comment] 2017-12-27 12:12
Duplicate of #100

**Closed by tillnagel** 2017-12-27 12:12 UTC
