### ISSUE TITLE
Map Tile Server has moved

### ISSUE THREAD

**Issue by dnnssgl** [tillnagel/unfolding#135] opened 2016-07-01 12:47 UTC
Hi,

I just fired up some old sketch using Unfolding Maps and I get the following error

`The file http://a.www.toolserver.org/tiles/bw-mapnik/10/552/338.png contains bad image data, or may not be an image.`

It seems that http://a.www.toolserver.org has moved their servers. Any news here?

**Comment by tillnagel** [comment] 2016-07-01 12:53
Strangely, entering that provided URL (http://a.www.toolserver.org/tiles/bw-mapnik/10/552/338.png) in a browser works for me, as it redirects to the correct one. http://a.tiles.wmflabs.org/bw-mapnik/10/552/338.png

In any case, duplicate of #100. Let's move the discussion over there.

**Closed by tillnagel** 2016-07-01 12:53 UTC
