### ISSUE TITLE
Default tiles unavailable

### ISSUE THREAD

**Issue by markusand** [tillnagel/unfolding#111] opened 2015-06-19 22:18 UTC
Hi!

I'm learning to use this amazing library. The first day everything worked perfectly, but since yesterday my sketch is unable to render the default tiles. I've tried with Microsoft Aerial, Simple Google and OpenMaps and everything works properly. For me the standard light grey tiles are perfect, but the error message makes me think about a server problem:

Unfolding Map v0.9.6
Using OpenGLMapDisplay with processing.opengl.PGraphics2D
java.io.IOException: Server returned HTTP response code: 500 for URL: http://a.tiles.wmflabs.org/bw-mapnik/2/1/2.png
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.URL.openStream(URL.java:1037)
	at processing.core.PApplet.createInputRaw(PApplet.java:7233)
	at processing.core.PApplet.createInput(PApplet.java:7201)
	at processing.core.PApplet.loadBytes(PApplet.java:7428)
	at processing.core.PApplet.loadImage(PApplet.java:5867)
	at de.fhpotsdam.unfolding.tiles.TileLoader.getTileFromUrl(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.TileLoader.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
The file "http://a.www.toolserver.org/tiles/bw-mapnik/2/1/2.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
 
(...) a long long error message.

Not sure how to move from here. Thanks

**Comment by tillnagel** [comment] 2015-06-20 12:04
Duplicate of #100 which I re-opened.

**Closed by tillnagel** 2015-06-20 12:04 UTC
