### ISSUE TITLE
Endless Errors on Simple Map Example

### ISSUE THREAD

**Issue by eric-souther** [tillnagel/unfolding#112] opened 2015-06-28 02:17 UTC
I'm running processing 2.2.1, OS X Yosemite 10.10.3, Java Version 8 (April 14, 2015). Can't seem to get even the simple examples to work, but I get pages and pages of these errors below:

Unfolding Map v0.9.6
Using OpenGLMapDisplay with processing.opengl.PGraphics2D
java.io.IOException: Server returned HTTP response code: 500 for URL: http://a.tiles.wmflabs.org/bw-mapnik/10/549/335.png
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at java.net.URL.openStream(URL.java:1037)
	at processing.core.PApplet.createInputRaw(PApplet.java:7233)
	at processing.core.PApplet.createInput(PApplet.java:7201)
	at processing.core.PApplet.loadBytes(PApplet.java:7428)
	at processing.core.PApplet.loadImage(PApplet.java:5867)
	at de.fhpotsdam.unfolding.tiles.TileLoader.getTileFromUrl(Unknown Source)
	at de.fhpotsdam.unfolding.tiles.TileLoader.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
The file "http://a.www.toolserver.org/tiles/bw-mapnik/10/549/335.png" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
java.io.IOException: Server returned HTTP response code: 500 for URL: http://a.tiles.wmflabs.org/bw-mapnik/10/550/335.png

I've look through the tutorials and can't find anything, does anyone no what I am doing wrong?

**Comment by tillnagel** [comment] 2015-06-29 09:03
Duplicate of #100. Please see there for a work-around.

**Closed by tillnagel** 2015-06-29 09:03 UTC
