### ISSUE TITLE
Ereur in !!

### ISSUE THREAD

**Issue by dhiaa05** [tillnagel/unfolding#150] opened 2017-06-26 13:54 UTC
hello
what is the Erreur in side image
how to solved!!
![problem](https://user-images.githubusercontent.com/29708536/27542473-a340f664-5a87-11e7-838f-1bf1d2fbfa32.jpg)

**Comment by tillnagel** [comment] 2017-06-26 13:57
Duplicate of #100.

Work-around: Use another map provider, or send us an e-mail to ask for Unfolding beta for Processing 3.

**Closed by tillnagel** 2017-06-26 13:57 UTC

**Comment by dhiaa05** [comment] 2017-06-26 14:10
thank you!! solved
but what is the importance of processing 3!!

**Comment by tillnagel** [comment] 2017-06-26 14:13
It is a newer version of Processing. See http://processing.org for more infos.
