### ISSUE TITLE
Image corrupted, any idea?

### ISSUE THREAD

**Issue by JorgeRui** [tillnagel/unfolding#152] opened 2017-10-01 15:15 UTC
When I try to use eclipse and start the first example "SimpleMapApp" it gives me this error:
The file http://a.www.toolserver.org/tiles/bw-mapnik/2/2/1.png contains bad image data, or may not be an image.

Any ideas?

**Comment by tillnagel** [comment] 2017-10-02 06:28
You need to switch to a different map provider, as the default one does not provides map tiles under the specified URL (and Processing does not recognize redirects).
See how to use other map providers at http://unfoldingmaps.org/tutorials/mapprovider-and-tiles.html#map-styles

Duplicate of #100. (Fixed in beta. Request beta via e-mail or DM)

**Closed by tillnagel** 2017-10-02 06:28 UTC
