### ISSUE TITLE
Marker not displaying on the map

### ISSUE THREAD

**Issue by iamgsshetty** [tillnagel/unfolding#169] opened 2019-12-08 04:53 UTC
code:-

import de.fhpotsdam.unfolding.*;
import de.fhpotsdam.unfolding.geo.*;
import de.fhpotsdam.unfolding.utils.*; 
import de.fhpotsdam.unfolding.providers.Microsoft;

import de.fhpotsdam.unfolding.marker.*;

UnfoldingMap map;

void setup() {
    size(800, 600);
    map = new UnfoldingMap(this,new Microsoft.AerialProvider());
    MapUtils.createDefaultEventDispatcher(this);
}

void draw() {
  map.draw();
  Location berlinLocation = new Location(52.5, 13.4);
  SimplePointMarker berlinMarker = new SimplePointMarker(berlinLocation);
  map.addMarkers(berlinMarker);
    
}

output on terminal:-

Unfolding Map v0.9.6
No OpenGL renderer. Using Java2DMapDisplay.

output:-
![ma](https://user-images.githubusercontent.com/45145698/70384457-b0d06600-19a4-11ea-87fc-164ee4b3e57a.PNG)

**Comment by tillnagel** [comment] 2019-12-08 17:02
Duplicate of #118. Use 

`size(800, 600, P2D);`

as work-around.

**Closed by tillnagel** 2019-12-08 17:02 UTC
